version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - npm install -g yarn
      - yarn install --frozen-lockfile

  build:
    commands:
      - echo "Building for $DEPLOY_ENV..."
      - yarn build --mode $DEPLOY_ENV

  post_build:
    commands:
      - echo "Build xong. Chuẩn bị đóng gói..."
      - cp appspec.yml dist/
      - cp -r scripts dist/

artifacts:
  files:
    - '**/*'
  base-directory: 'dist'

cache:
  paths:
    - 'node_modules/**/*'
    - '$(yarn cache dir)/**/*'
