server {
    listen 80;

    # Tăng giới hạn upload (mặc định Nginx chỉ có 1MB)
    client_max_body_size 50M;

    index index.php index.html;

    # SPA Mode: Nếu lỗi 404 thì đẩy về index.html để Vue Router xử lý
    error_page 404 = /index.html;

    # =====================================================
    # 1. FRONTEND (VUE.JS)
    # =====================================================
    location / {
        root /var/www/laravel-vue/web/current; # Thư mục chứa index.html của Vue.js
        # Kiểm tra file vật lý, nếu không có thì trả về index.html (cho Vue Router)
        try_files $uri $uri/ /index.html;
    }

    # =====================================================
    # 2. MEDIA & UPLOAD (LARAVEL STORAGE)
    # =====================================================
    location ~ ^/storage/ {
        # Trỏ thẳng vào public của API (nơi chứa symlink 'storage')
        root /var/www/laravel-vue/api/current/public;

        try_files $uri =404;

        # Tối ưu hóa: Cache trình duyệt 1 năm & tắt log để nhẹ server
        expires 1y;
        add_header Cache-Control "public, no-transform";

        # CORS: Cho phép Frontend khác domain lấy tài nguyên (ảnh/video)
        add_header Access-Control-Allow-Origin *;
        access_log off;
    }

    # =====================================================
    # 3. BACKEND (LARAVEL API)
    # =====================================================
    location /api {
        root /var/www/laravel-vue/api/current/public;
        # Nếu không tìm thấy file, đẩy request vào Laravel (index.php)
        try_files $uri $uri/ /index.php?$query_string;
    }

    # Xử lý nội bộ cho Laravel (Entry point)
    location = /index.php {
        internal; # Chặn user truy cập trực tiếp qua domain.com/index.php

        root /var/www/laravel-vue/api/current/public;
        fastcgi_intercept_errors on;
        fastcgi_index  index.php;
        include        fastcgi_params;
        fastcgi_param  SCRIPT_FILENAME  $realpath_root$fastcgi_script_name;
        fastcgi_param  PATH_INFO $fastcgi_path_info;
        server unix:/run/php-fpm/www.sock;
    }

    # =====================================================
    # 4. SECURITY
    # =====================================================

    # Chặn thực thi file PHP lạ ở thư mục Frontend, ép về index.html
    location ~ \.php$ {
        root /var/www/laravel-vue/web/current;
        rewrite ^ /index.html break;
    }

    # Chặn truy cập các file nhạy cảm (ví dụ: .env, .git)
    location ~ /\. {
        deny all;
    }
}